'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''


generate_triangle = lambda n: ((n*(n+1)) / 2)
generate_pentagonal = lambda n: (n*((3*n) - 1)) / 2
generate_hexagonal = lambda n: n*((2*n) - 1)

tri_list = []
pent_list = []
hex_list = []

counter = 1

while True:
    tri_list.append(generate_triangle(counter))
    pent_list.append(generate_pentagonal(counter))
    hex_list.append(generate_hexagonal(counter))
    if counter % 1000 == 0:
        if len(set(tri_list) & set(pent_list) & set(hex_list)) == 3:
            break
    counter = counter + 1

print(set(tri_list) & set(pent_list) & set(hex_list))



